"use client";
import type { Metadata } from "next";
import { rubik300, rubik500, rubik700 } from "@/assets/fonts";
import Menu from "@/components/Menu";
import { GlobalStyle, Row } from "@/styles";
import { ThemeProvider } from "styled-components";
import StyledComponentsRegistry from "@/lib/registry";
import * as S from "./styles";
import { theme } from "@/styles/theme";
import Header from "@/components/Header";
import { HeaderProvider, useHeader } from "@/hooks/useHeader";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  const { isOpenMenu } = useHeader();
  return (
    <html
      lang="en"
      className={`${rubik300.variable} ${rubik700.variable} ${rubik500.variable}`}
    >
      <body>
        <ThemeProvider theme={theme}>
          <StyledComponentsRegistry>
            <GlobalStyle whiteColor />
            <Header />
            <Menu isOpen={isOpenMenu} />

            <S.WrapperPage>{children}</S.WrapperPage>
          </StyledComponentsRegistry>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default function Root({ children }: { children: React.ReactNode }) {
  return (
    <HeaderProvider>
      <RootLayout>{children}</RootLayout>
    </HeaderProvider>
  );
}
